# craindo o compose para a aplicação
# kubedev.
#criando o serviço postgre
services:
  postgre:
    image: postgres:${POSTGRES_TAG}
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgre_docker_vol:/var/lib/postgresql/data
    networks:
      - kubenews_net  
#criando o serviço kubenews
  kubenews:
    image: kubedevio/kube-news:${KN_TAG}
    ports:
      - 8080:8080
    environment:
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_USERNAME: ${POSTGRES_USER}
      DB_DATABASE: ${POSTGRES_DB}
      DB_HOST: postgre
    networks:
      - kubenews_net
    depends_on:
      - postgre

#criando o volume gerenciado
volumes:
  postgre_docker_vol:     
    name: postgre_exemplo_vol 

networks:
  kubenews_net:
    driver: bridge